/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */


/**
 * @file    queue_recov_db.c
 *
 * @brief
 *		queue_recov_db.c - This file contains the functions to record a queue
 *		data structure to database and to recover it from database.
 *
 *		The data is recorded in the database
 */

#include <pbs_config.h>   /* the master config generated by configure */

#include <sys/types.h>
#include <sys/param.h>
#include "pbs_ifl.h"
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "server_limits.h"
#include "list_link.h"
#include "attribute.h"
#include "job.h"
#include "reservation.h"
#include "queue.h"
#include "log.h"
#include "pbs_nodes.h"
#include "svrfunc.h"
#include "pbs_db.h"


#ifndef PBS_MOM
extern pbs_db_conn_t	*svr_db_conn;
#endif

/**
 * @brief
 *		convert queue structure to DB format
 *
 * @param[in]	pque	- Address of the queue in the server
 * @param[out]	pdbque  - Address of the database queue object
 *
 * @retval   -1  Failure
 * @retval	>=0 What to save: 0=nothing, OBJ_SAVE_NEW or OBJ_SAVE_QS
 */
static int
que_2_db(pbs_queue *pque, pbs_db_que_info_t *pdbque)
{
	int savetype = 0;

	strcpy(pdbque->qu_name, pque->qu_qs.qu_name);
	pdbque->qu_type = pque->qu_qs.qu_type;
	strcpy(pdbque->qu_savetm, pque->qu_savetm);

	if ((encode_attr_db(que_attr_def, pque->qu_attr, (int)QA_ATR_LAST, &pdbque->cache_attr_list, &pdbque->db_attr_list, 0)) != 0)
		return -1;

	if (pque->qu_savetm[0] == '\0') /* object was never saved or loaded before */
		savetype |= (OBJ_SAVE_NEW | OBJ_SAVE_QS);

	if (obj_qs_modified(&pque->qu_qs, sizeof(pque->qu_qs), pque->qs_hash) == 1) {
		savetype |= OBJ_SAVE_QS;
		pdbque->qu_type = pque->qu_qs.qu_type;
	}

	return savetype;
}

/**
 * @brief
 *		convert from database to queue structure
 *
 * @param[out]	pque	- Address of the queue in the server
 * @param[in]	pdbque	- Address of the database queue object
 *
 *@return 0      Success
 *@return !=0    Failure
 */
static int
db_2_que(pbs_queue *pque, pbs_db_que_info_t *pdbque)
{
	strcpy(pque->qu_qs.qu_name, pdbque->qu_name);
	pque->qu_qs.qu_type = pdbque->qu_type;

	if ((decode_attr_db(pque, &pdbque->cache_attr_list, &pdbque->db_attr_list, que_attr_def, pque->qu_attr, (int) QA_ATR_LAST, 0)) != 0)
		return -1;

	obj_qs_modified(&pque->qu_qs, sizeof(pque->qu_qs), pque->qs_hash);

	strcpy(pque->qu_savetm, pdbque->qu_savetm);

	return 0;
}

/**
 * @brief
 *	Save a queue to the database
 *
 * @param[in]	pque  - Pointer to the queue to save
 * @param[in]	mode:
 *		QUE_SAVE_FULL - Save full queue information (update)
 *		QUE_SAVE_NEW  - Save new queue information (insert)
 *
 * @return      Error code
 * @retval	0 - Success
 * @retval	1 - Failure
 *
 */

int
que_save_db(pbs_queue *pque)
{
	pbs_db_que_info_t	dbque = {{0}};
	pbs_db_obj_info_t	obj;
	pbs_db_conn_t *conn = (pbs_db_conn_t *) svr_db_conn;
	int savetype;
	int rc = -1;

	if ((savetype = que_2_db(pque, &dbque)) == -1)
		goto done;
	
	obj.pbs_db_obj_type = PBS_DB_QUEUE;
	obj.pbs_db_un.pbs_db_que = &dbque;

	if (pbs_db_save_obj(conn, &obj, savetype) == 0) {
		strcpy(pque->qu_savetm, dbque.qu_savetm);
		rc = 0;
	}

done:
	free_db_attr_list(&dbque.db_attr_list);
	free_db_attr_list(&dbque.cache_attr_list);
	
	if (rc != 0) {
		strcpy(log_buffer, "que_save failed ");
		if (conn->conn_db_err != NULL)
			strncat(log_buffer, conn->conn_db_err, LOG_BUF_SIZE - strlen(log_buffer) - 1);
		log_err(-1, __func__, log_buffer);

		panic_stop_db(log_buffer);
	}
	return rc;
}


/**
 * @brief
 *	Utility function called to allocate and decode queue structure
 *
 * @param[in]	pq    - If pq exists in heap, pointer to that, else NULL
 * @param[in]	dbque - Pointer to the database structure of a job
 *
 * @retval	 NULL - Failure
 * @retval	!NULL - Success, pointer to que structure recovered
 *
 */
pbs_queue *
que_recov_db_spl(pbs_queue *pq, pbs_db_que_info_t *dbque)
{
	pbs_queue *pqt = NULL;

	if (!pq) {
		pqt = que_alloc(dbque->qu_name);
		pq = pqt;
	}
	
	if (pq) {
		if (db_2_que(pq, dbque) == 0)
			return (pq);
	}

	/* error case */
	if (pqt)
		que_free(pqt); /* free if we allocated here */

	snprintf(log_buffer, LOG_BUF_SIZE, "Failed to decode queue %s", dbque->qu_name);
	log_err(-1, __func__, log_buffer);

	return (NULL);
}


/**
 * @brief
 *		Recover a queue from the database
 *
 * @param[in]	qname	- Name of the queue to recover
 * @param[out]  pq - Queue pointer, if any, to be updated
 *
 * @return	The recovered queue structure
 * @retval	NULL	- Failure
 * @retval	!NULL	- Success - address of recovered queue returned
 *
 */
pbs_queue *
que_recov_db(char *qname, pbs_queue	*pq)
{
	pbs_db_que_info_t	dbque = {{0}};
	pbs_db_obj_info_t	obj;
	pbs_db_conn_t		*conn = (pbs_db_conn_t *) svr_db_conn;
	int rc = -1;

	if (pq) {
		CHECK_ALREADY_LOADED(pq);
		strcpy(dbque.qu_savetm, pq->qu_savetm);
	} else
		dbque.qu_savetm[0] = '\0';

	strcpy(dbque.qu_name, qname);
	obj.pbs_db_obj_type = PBS_DB_QUEUE;
	obj.pbs_db_un.pbs_db_que = &dbque;

	rc = pbs_db_load_obj(conn, &obj);
	if (rc == -2)
		return pq; /* no change in que, return the same pq */

	if (rc == 0) {
		pq = que_recov_db_spl(pq, &dbque);
	}
	
	free_db_attr_list(&dbque.db_attr_list);
	free_db_attr_list(&dbque.cache_attr_list);

	return pq;
}

/**
 * @brief
 *	Refresh/retrieve queue from database and add it into AVL tree if not present
 *
 *	@param[in]	dbque - The pointer to the wrapper queue object of type pbs_db_que_info_t
 *  @param[in]  refreshed - To count the no. of queues refreshed
 *
 * @return	The recovered queue
 * @retval	NULL - Failure
 * @retval	!NULL - Success, pointer to queue structure recovered
 *
 */
pbs_queue *
refresh_queue(pbs_db_que_info_t *dbque, int *refreshed) 
{
	char  *pc;
	pbs_queue *pque = NULL;
	char   qname[PBS_MAXDEST + 1];
	extern pbs_list_head	svr_queues; 

	*refreshed = 0;
	
	(void)strncpy(qname, dbque->qu_name, PBS_MAXDEST);
	qname[PBS_MAXDEST] ='\0';
	pc = strchr(qname, (int)'@');	/* strip off server (fragment) */
	if (pc)
		*pc = '\0';
	/* get the old pointer of the queue, if queue is already in memory */
	pque = (pbs_queue *)GET_NEXT(svr_queues);
	while (pque != NULL) {
		if (strcmp(qname, pque->qu_qs.qu_name) == 0)
			break;
		pque = (pbs_queue *)GET_NEXT(pque->qu_link);
	}
	if (pc)
		*pc = '@';	/* restore '@' server portion */

	if (pque) {
		if (strcmp(dbque->qu_savetm, pque->qu_savetm) != 0) {
			if (db_2_que(pque, dbque) != 0)
				goto err;

			*refreshed = 1;
		}
	} else {
		if ((pque = que_recov_db_spl(pque, dbque)) == NULL) /* if job is not in AVL tree, load the job from database */
			goto err;	
	
		append_link(&svr_queues, &pque->qu_link, pque);
		*refreshed = 1;
	}
	return pque;

err:
	snprintf(log_buffer, LOG_BUF_SIZE, "Failed to refresh queue %s", dbque->qu_name);
	log_err(-1, __func__, log_buffer);
	return NULL;
}